const COLORS={0:"#FFFFFF",1:"#B7b7b7",2:"#6b6b6b",3:"#000000",4:"#441111",5:"#7c0000",6:"#E30613",7:"#C64646",8:"#Ffdbb4",9:"#Ffad55",10:"#Ff8400",11:"#713b00",12:"#97701d",13:"#EFAC1F",14:"#Fdf100",15:"#Cbff34",16:"#3fff00",17:"#0a9343",18:"#006110",19:"#004634",20:"#00926d",21:"#00ffcc",22:"#2fc9ff",23:"#0074AE",24:"#0032ae",25:"#030e77",26:"#2f1748",27:"#490095",28:"#9700ff",29:"#Ff00e1",30:"#D97A9E",31:"#Ffafe0"};async function synchronizeCanvas(){const canvas=document.querySelector(".canvas");const ctx=canvas.getContext("2d");const response=await fetch('data.bin');const boardBytes=await response.arrayBuffer();const board=new Uint8Array(boardBytes);for(let y=0;y<height;y++){for(let x=0;x<width;x++){const offset=x+width*y;const colorIndex=board[offset];const color=COLORS[colorIndex];ctx.fillStyle=color;ctx.fillRect(x,y,1,1);}}}
synchronizeCanvas();const canvas=document.querySelector(".canvas");canvas.style.top=window.innerHeight*(50 / 100)+'px';canvas.style.left=window.innerWidth*(50 / 100)+'px';const context=canvas.getContext("2d",{willReadFrequently:true});window.onload=function(){let moved=false;var ctx=canvas.getContext("2d",{willReadFrequently:true});var zoomLevel=isMobile()?0.25*(1000 / P):0.5*(1000 / P);const zoomMin=zoomLevel;var zoomSpeed=isMobile()?40:10;function resizeCanvas(canvas,ctx,zoomLevel){moved=true;var ratio=canvas.width / canvas.height;var newWidth=P*zoomLevel;var newHeight=newWidth / ratio;canvas.style.width=newWidth+"px";canvas.style.height=newHeight+"px";}
function isMobile(){return /Mobi|Android/i.test(navigator.userAgent);}
const hover=document.querySelector(".hover-canvas");const icon=document.querySelector(".hover-container");function canvas2Size(){const canvasWidth=canvas.offsetWidth;const canvasHeight=canvas.offsetHeight;const hoverWidth=hover.offsetWidth;const hoverHeight=hover.offsetHeight;const scaleX=canvasWidth / hoverWidth;const scaleY=canvasHeight / hoverHeight;hover.style.transform=`translate(-50%,-50%)scale(${scaleX},${scaleY})`;hover.style.width=P+'px';hover.style.height=P+'px';hover.style.top=canvas.style.top;hover.style.left=canvas.style.left;}
let zoomed=false;function wheel(canvas,ctx){window.addEventListener("wheel",handleZoom);window.addEventListener("touchstart",handleTouchStart);window.addEventListener("touchmove",handleTouchMove);window.addEventListener("touchend",handleTouchEnd);function handleZoom(event){var mouseX=event.clientX-canvas.offsetLeft;var mouseY=event.clientY-canvas.offsetTop;var prevWidth=canvas.offsetWidth;var prevHeight=canvas.offsetHeight;var zoomDirection=event.deltaY<0?1:-1;border=false;zoomLevel=zoomLevel+(zoomSpeed*zoomDirection*(zoomLevel / 50));zoomLevel=Math.max(zoomMin,Math.min(70,zoomLevel));resizeCanvas(canvas,ctx,zoomLevel);var newWidth=canvas.offsetWidth;var newHeight=canvas.offsetHeight;var deltaX=mouseX*(newWidth-prevWidth)/ prevWidth;var deltaY=mouseY*(newHeight-prevHeight)/ prevHeight;canvas.style.top=(canvas.offsetTop-deltaY)+"px";canvas.style.left=(canvas.offsetLeft-deltaX)+"px";getCenterCoordinate(canvas);}
var initialDistance,initialScale;function handleTouchStart(event){zoomed=false;if(event.touches.length===2){var touch1=event.touches[0];var touch2=event.touches[1];initialDistance=Math.sqrt(Math.pow(touch2.clientX-touch1.clientX,2)+
Math.pow(touch2.clientY-touch1.clientY,2));initialScale=zoomLevel;}}
function handleTouchMove(event){moved=true;if(event.touches.length===2){moved=true;var touch1=event.touches[0];var touch2=event.touches[1];var currentDistance=Math.sqrt(Math.pow(touch2.clientX-touch1.clientX,2)+
Math.pow(touch2.clientY-touch1.clientY,2));var scale=currentDistance / initialDistance;var mouseX=(touch1.clientX+touch2.clientX)/ 2-canvas.offsetLeft;var mouseY=(touch1.clientY+touch2.clientY)/ 2-canvas.offsetTop;var prevWidth=canvas.offsetWidth;var prevHeight=canvas.offsetHeight;zoomLevel=initialScale*scale;zoomLevel=Math.max(zoomMin,Math.min(70,zoomLevel));resizeCanvas(canvas,ctx,zoomLevel);var newWidth=canvas.offsetWidth;var newHeight=canvas.offsetHeight;var deltaX=mouseX*(newWidth-prevWidth)/ prevWidth;var deltaY=mouseY*(newHeight-prevHeight)/ prevHeight;canvas.style.top=(canvas.offsetTop-deltaY)+"px";canvas.style.left=(canvas.offsetLeft-deltaX)+"px";getCenterCoordinate(canvas);}}
function handleTouchEnd(event){initialDistance=null;initialScale=zoomLevel;if(moved===true){zoomed=true;}}}
let clicked=false;let dragged=false;let border=false;var minX=0;var maxX=P-1;var minY=0;var maxY=P-1;let prevX,prevY;let lastMouseX=0;let lastMouseY=0;let mouseDownX=0;let mouseDownY=0;wheel(canvas,ctx);resizeCanvas(canvas,ctx,zoomLevel);canvas.style.left="50%";canvas.style.top="50%";canvas2Size();getCenterCoordinate();function getCenterCoordinate(){const rect=canvas.getBoundingClientRect();const coordinate=document.querySelector('.xy');const centerX=window.innerWidth / 2;const centerY=window.innerHeight / 2;let x=Math.floor(((centerX-rect.left)/ zoomLevel));let y=Math.floor(((centerY-rect.top)/ zoomLevel));const screenX=x*zoomLevel;const screenY=y*zoomLevel;if(x<minX){x=minX;border=true;canvas.style.left=((rect.width / 2)+centerX)+"px";}
if(x>maxX){x=maxX;border=true;canvas.style.left=(centerX-(rect.width / 2))+"px";}
if(y<minY){y=minY;border=true;canvas.style.top=((rect.height / 2)+centerY)+"px";}
if(y>maxY){y=maxY;border=true;canvas.style.top=(centerY-(rect.height / 2))+"px";}
if(x!==prevX||y!==prevY){icon.style.transform=`translate(${x}px,${y}px)scale(0.01)`;icon.style.transformOrigin='top left';icon.style.imageRendering='pixelated';prevX=x;prevY=y;}
canvas2Size();coordinate.innerHTML='('+x+','+y+')';return{x:x,y:y};}
window.addEventListener('keyup',function(){const icon=document.querySelector('.hover-container');const rect=icon.getBoundingClientRect();if(event.key==='w'||event.key==='ArrowUp'){canvas.style.top=(parseInt(canvas.style.top.slice(0,-2))+rect.height)+'px';getCenterCoordinate();}
else if(event.key==='a'||event.key==='ArrowLeft'){canvas.style.left=(parseInt(canvas.style.left.slice(0,-2))+rect.width)+'px';getCenterCoordinate();}
else if(event.key==='s'||event.key==='ArrowDown'){canvas.style.top=(parseInt(canvas.style.top.slice(0,-2))-rect.height)+'px';getCenterCoordinate();}
else if(event.key==='d'||event.key==='ArrowRight'){canvas.style.left=(parseInt(canvas.style.left.slice(0,-2))-rect.width)+'px';getCenterCoordinate();}
else if(event.key===' '){const centerCoordinate=getCenterCoordinate();if(selectedColorIndex!==null){ctx.globalAlpha=1;placePixel(centerCoordinate.x,centerCoordinate.y,selectedColorIndex);}}});function copyToClipboard(text){navigator.clipboard.writeText(text).then(()=>{}).catch((err)=>{});}
if('ontouchstart'in window){window.addEventListener("touchstart",function(e){e.preventDefault();clicked=true;lastMouseX=e.touches[0].clientX;lastMouseY=e.touches[0].clientY;mouseDownX=e.touches[0].clientX;mouseDownY=e.touches[0].clientY;});window.addEventListener("touchmove",function(e){moved=true;e.preventDefault();if(clicked===true){const deltaX=e.touches[0].clientX-lastMouseX;const deltaY=e.touches[0].clientY-lastMouseY;border=false;canvas.style.top=canvas.offsetTop+deltaY+"px";canvas.style.left=canvas.offsetLeft+deltaX+"px";lastMouseX=e.touches[0].clientX;lastMouseY=e.touches[0].clientY;dragged=true;canvas2Size();getCenterCoordinate(canvas);}});window.addEventListener("touchend",function(e){e.preventDefault();clicked=false;if(moved===false){canvas.addEventListener("touchend",function(e){if(moved===false&&event.touches.length<2&&zoomed===false){const centerCoordinate=getCenterCoordinate();placePixel(centerCoordinate.x,centerCoordinate.y,selectedColorIndex);}});}
else{moved=false;}});}
else{window.addEventListener("mousedown",function(e){getCenterCoordinate(canvas);clicked=true;lastMouseX=e.clientX;lastMouseY=e.clientY;mouseDownX=e.clientX;mouseDownY=e.clientY;});window.addEventListener("mousemove",function(e){if(clicked===true){const deltaX=e.clientX-lastMouseX;const deltaY=e.clientY-lastMouseY;const rect=canvas.getBoundingClientRect();const centerX=window.innerWidth / 2;const centerY=window.innerHeight / 2;let x=centerX-(rect.width / 2);let y=centerY-(rect.height / 2);border=false;canvas.style.left=canvas.offsetLeft+deltaX+"px";canvas.style.top=canvas.offsetTop+deltaY+"px";lastMouseX=e.clientX;lastMouseY=e.clientY;dragged=true;canvas2Size();getCenterCoordinate(canvas);}});window.addEventListener("mouseup",function(e){clicked=false;});}};